// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_render.ts";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/links.tsx";
import * as $4 from "./routes/posts.tsx";
import * as $5 from "./routes/projects.tsx";

const manifest = {
  routes: {
    "./routes/_render.ts": $0,
    "./routes/about.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/links.tsx": $3,
    "./routes/posts.tsx": $4,
    "./routes/projects.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
